### ISSUE TITLE
.sass files not supported

### ISSUE THREAD

**Issue by rhanb** [toddanglin/nativescript-dev-sass#16]
Hi,

I'm using nativescript-dev-sass in a project using Angular and Nativescript but i'm using .sass files and not .scss files, could it be supported?

Thanks

**Comment by toddanglin** [comment]
Definitely could be.

There are a handful of places in the `converter.js` and `after-prepare.js` files where this pattern is used to find files that will be parsed: `app/**/*.scss`

To extend support for `*.sass`, this pattern just needs to be updated. Don't have time directly to test, but if you want to test a patch and submit a PR, I'll happily merge!

**Comment by toddanglin** [comment]
This will be supported in the next release (1.0.0). Available today as an RC release on NPM.

Support added with PR from @PeterStaev (#22)
