### ISSUE TITLE
Unable to sync files

### ISSUE THREAD

**Issue by theCSSguru** [toddanglin/nativescript-dev-sass#18]
Upgraded to Nativescript 2.5, and I get this error when trying to save with tns run android:

`Unable to sync files. Error is: ENOENT: no such file or directory, stat '/Volumes/Storage/LocallyEpic/LocallyEpic/_App/_git
/locallyepicapp/platforms/android/src/main/assets/app/views/login/_login.scss'`

When I look in that directory it's not there, like it says. Should it be?

*NOTE* - this only happens when I use the tns run android (haven't tested ios) which now has the built in live sync, and I change some CSS in the Scss file and save it, I get the above error.

**Comment by ghost** [comment]
I have the same issue since I've upgraded to Nativescript 2.5

**Comment by danieloprado** [comment]
same

**Comment by toddanglin** [comment]
I've encountered this error with other files using {N} 2.5, so I think it may be a bug in 2.5 related to LiveSync. Possibly this: https://github.com/NativeScript/nativescript-cli/issues/2476

Are you able sync files the first time you run `tns run ios`? I assume you are hitting the error on subsequent saves and attempts to sync?

**Comment by theCSSguru** [comment]
Hmm ok, I see you posted there as well about it, hopefully they will resolve it soon, otherwise I suppose i'm back to using Vanilla CSS right? or Would that not sync still, haven't tried it.

**Comment by thakurarun** [comment]
I am facing the same, it seems livesync is broken. It work fine for first time but on changing *.scss file I start having this issue. Please resolve asap.

**Comment by mauriciomelo** [comment]
I am facing the same issue with android and iOS.

**Comment by ludwiktrammer** [comment]
> Are you able sync files the first time you run tns run ios? I assume you are hitting the error on subsequent saves and attempts to sync?

I'm experiencing the same issue and the answer is "yes". I'm able to run the app using "tns run android", but as soon as I touch a single .scss file NativeScript tries to sync and everything blow ups.

**Comment by tskweres** [comment]
same issue 👍

**Comment by elvismercado** [comment]
Me too, running on ios tns v2.5. Whenever i do a change it refreshes that change first and then it also sync the app.css file for some reason every time. Here's what is see in my terminal

```
Refreshing application...
Feb  8 08:52:10 [me] com.apple.CoreSimulator.SimDevice.[id]: Service exited due to Terminated: 15
Successfully synced application org.nativescript.appname on device [id].

Skipping prepare.
Transferring project files...
Successfully transferred app.css.
Successfully transferred app.css.
Refreshing application...
```

**Comment by toddanglin** [comment]
Yep. I'm experiencing the same behavior. It's a LiveSync issue in 2.5.

It has been patched and should be resolved in the 2.5.1 release:
https://github.com/NativeScript/nativescript-cli/pull/2508

Closing this issue for now. If the problem persists after 2.5.1, feel free to re-open.

**Comment by elvismercado** [comment]
@toddanglin tns 2.5.1 is out but i am still experiencing the same issue. Maybe even worse now :(
Odd thing is that only tns is at version 2.5.1
tns-ios and tns-android are still on 2.5.0

**Comment by randy-johnson** [comment]
@elvismercado Did you tns platform remove android  tns platform add android and the same for IOS?  2.5.1 has been working for our sass project.

**Comment by toddanglin** [comment]
@elvismercado Are you using the `nativescript-i18n` plugin? If so, there is a bit of a nasty issue with that plugin and the 2.5.1. CLI. See this issue for more details: https://github.com/NativeScript/nativescript-cli/issues/2557

Meanwhile, your `tns-ios` and `tns-android` versions are correct. The CLI and `tns-core-modules` were bumped to 2.5.1, but the platform runtimes were not.

**Comment by elvismercado** [comment]
@randy-johnson i've done dath. i even do `rm -rf node_modules platforms`. Each time i do a change it detects the change file and a second after it also detects `app.css` changed, resulting in a double restart of the app. I have a setInterval which keeps duplicating in the background each time the app restarts. I don't know if it is this isue that is causing the problem anymore or if it is the interval.

@toddanglin i am not using `nativescript-i18n`

**Comment by toddanglin** [comment]
I think this issue would be better discussed in the NativeScript CLI project. It's definitely related to recent changes in the {N} CLI causing "double builds" in some cases (and not specific the SASS plugin). I'd suggest sharing your scenario in this thread:

https://github.com/NativeScript/nativescript-cli/issues/2482

Hopefully a patch to the CLI will soon resolve all of these problems.

**Comment by elvismercado** [comment]
thnx @toddanglin , i'll try posting there
