### ISSUE TITLE
Modification Ignored

### ISSUE THREAD

**Issue by Jufik** [toddanglin/nativescript-dev-sass#2]
When coding on SCSS files (with livesync), modifications will appear the second time.
when loading the first time, CSS is compiled, but result not taken into account (looks like the app i build over the previous css version)

**Comment by toddanglin** [comment]
Cleaning-up an old issue.

Check-out the next major version (1.0.0) of the plugin and see if this problem still exists. Major refactoring from #25 probably addresses this. If the problem persists, let me know.
