### ISSUE TITLE
Error on NativeScript 3 RC-1 : First call of getPlatformData without providing projectData.

### ISSUE THREAD

**Issue by kbarralon** [toddanglin/nativescript-dev-sass#23]
I get this error with NativeScript 3 RC-1 when I run `tns run android` : `First call of getPlatformData without providing projectData.`

**Comment by hypery2k** [comment]
getting the same error

**Comment by toddanglin** [comment]
Sorry for the trouble! This has been patched. Try the latest version and let me know if you still have trouble:

```
$ tns plugin remove nativescript-dev-sass
$ tns plugin add nativescript-dev-sass@rc --save-dev
```

If everything is working correctly, I'll drop the RC version when NativeScript 3.0.0 ships.

**Comment by theAl** [comment]
Hi @toddanglin,
unfortunately I am still getting this error. I use `nativescript@3.0`, `nativescript-dev-sass@1.1.1` and `angular@4.0.1` and trying to build an ios app. Can you please have a look again? I don't know how to fix it. This error occurs after `tns build ios`.

Thanks

**Comment by toddanglin** [comment]
Can you try running the demo that is part of this repo and let me know if you still encounter the problem? I do not see that error, but if you can reproduce it, that will help track down what might be happening.

**Comment by theAl** [comment]
Yes ok, I'll try that today and will give you feedback.

**Comment by theAl** [comment]
So the demo App runs for me. I'll compare it with my project now. Thanks for your help!
