### ISSUE TITLE
Use tilde to import files in node_modules

### ISSUE THREAD

**Issue by ishitatsuyuki** [toddanglin/nativescript-dev-sass#24]
Although `~`(tilde) is a webpack extension, we're familiar with it at many places (angular-cli, and webpack for NS handles it). I'm proposing to implement it with a custom resolver.

The solution is already provided on [SO](https://stackoverflow.com/questions/37106230/node-sass-does-not-understand-tilde).

**Comment by toddanglin** [comment]
The latest version of the plugin (1.0.0-rc) directly uses the Node Sass CLI to transpile files. So, to support this in the plugin, we need to either: A) wait for Node Sass to directly support WebPack style imports, or B) add a custom importer directly to the plugin.

Fortunately, Option B does seem to be supported with the CLI (https://github.com/sass/node-sass#usage-1). And I don't see many downsides to supporting this out-of-the-box. Will experiment with a custom importer and try to include in the 1.0.0 official release.

**Comment by toddanglin** [comment]
Okay. This was pretty straightforward to add (Commit: bd28c67b1847aa0496d803bbb119cf111afd7431). It's now supported in the v1.0.0 latest release.

Thanks for the suggestion. Let me know if it improves your experience with webpack.
