### ISSUE TITLE
Update closes app

### ISSUE THREAD

**Issue by lukeramsden** [toddanglin/nativescript-dev-sass#27]
This plugin seems to break the hot-reloading feature of NativeScript by closing and reopening the app on every change. Is there a way to make it hotreload?

**Comment by toddanglin** [comment]
With the latest versions of the plugin (1.x +), this should only happen in NativeScript versions lower than 2.5. So if you're using NativeScript 2.4 or lower, a LiveSync will cause the app to fully reload when using this plugin.

If you don't plan to upgrade to {N} 2.5.x or 3.0.0 soon, I suggest you use an older version of this plugin that DOES support hot reload in older versions of NativeScript. You can find details in the README, but here's how you can install an older version of the plugin:
```
$ npm install nativescript-dev-sass@0.4.2 --save-dev
```

In newer versions of NativeScript, LiveSync/hotreload should work as expected with this plugin.

Hope that helps.
