### ISSUE TITLE
Using this lib results in iOS App Store rejection issue - related to `node-sass` dependency

### ISSUE THREAD

**Issue by NathanWalker** [toddanglin/nativescript-dev-sass#3]
I'm not sure how to solve this just yet, but I ran into this tonight while trying to upload an app to the iOS App Store:

> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'ShoutOutPlay.app/app/tns_modules/node-sass/vendor/darwin-x64-47/binding.node' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'ShoutOutPlay.app/app/tns_modules/node-sass/vendor/darwin-x64-47/binding.node' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
> 
> ERROR ITMS-90512: "Invalid sdk value. The value provided for the sdk portion of LC_VERSION_MIN_MACOSX in ShoutOutPlay.app/app/tns_modules/node-sass/vendor/darwin-x64-47/binding.node is 10.11 which is greater than the maximum allowed value of 10.0."
> ERROR ITMS-90512: "Invalid sdk value. The value provided for the sdk portion of LC_VERSION_MIN_MACOSX in ShoutOutPlay.app/app/tns_modules/node-sass/vendor/darwin-x64-47/binding.node is 10.11 which is greater than the maximum allowed value of 10.0."

Going into the archive and manually removing the `node-sass/vendor` folder allows the app store submittal to proceed. If a solution comes to mind to fix here, I'll submit a PR, not sure.

**Comment by toddanglin** [comment]
Interesting. I wonder if any of NativeScript's build step hooks could be used to remove this folder? Not sure how to solve either, but will think about it, too. Thanks for reporting the issue!

**Comment by NathanWalker** [comment]
Using a webpack build does get away from this issue so I'm going to close this for now. Since using the webpack plugin to create production builds for deployment across the stores should be the standard.

**Comment by toddanglin** [comment]
I'm sure it could benefit others to see what you're doing with webpack, both to resolve this issue and generally improve production builds. If you end-up blogging about it, feel free to share a link here. Probably good fodder for improving the README for this plugin, too.

**Comment by dotdreaming** [comment]
Hi guys, I have the same error. How do you use webpack in the build to get round this?

**Comment by toddanglin** [comment]
Now that there is a post-build step in this plugin, I think we could add an additional action to auto-remove this `node-sass` folder. I don't think there is any reason to include it in the final build output. Let me take a fresh look.

**Comment by dotdreaming** [comment]
That would be awesome

**Comment by NathanWalker** [comment]
@dotdreaming @toddanglin this works really well too if you run into webpack struggles:
https://www.npmjs.com/package/nativescript-hook-filter-modules
Works really well. 👍

**Comment by toddanglin** [comment]
Okay. The fix is in and the plugin is version bumped to 0.4.1. The `node-sass` directory will now be auto-deleted. Nathan's suggestion is great, too, for cleaning-up other unneeded runtime modules.

**Comment by dotdreaming** [comment]
Excellent.
I used hook-filter-modules and it worked a treat!
