### ISSUE TITLE
app.android.scss and app.ios.scss not being converted to css files

### ISSUE THREAD

**Issue by kamok** [toddanglin/nativescript-dev-sass#37]
I'm following the instructions on https://docs.nativescript.org/ui/theme#sass-usage

After doing `tns install sass`, I create 3 files inside the `app` dir. `_app-common.scss`, `app.android.scss`, and `app.ios.scss`.

Then I copy paste the code snippets on that doc. 

The custom scss files work. For example, I have a `app/pages/login/login.scss` that gets converted into `login.css` Livereload also works.

However, the 2 `app.android.scss` and `app.ios.scss` does not convert to `.css`.

Any ideas?

**Comment by davorpeic** [comment]
Ok, 
I had the same issue, and I think I found a solution. 

My first test was running `tns run android --justlaunch` in place of standard `tns run android`, that generated my css file, but device was still saying "no css file" even it was generated, so I checked permissions on file and they were set to 644, I changed just my component css to 755 and then NS could see the css file. My next move was apply 755 to entire pages folder and files. After that even if I deleted my component css and run `tns run android` which generated my css file and activated livesync.

Can you try and see if this fixes your issue?

**Comment by toddanglin** [comment]
Thanks for the tip, @davorpeic.

@kamok Can you confirm if permissions were the problem in your case? In general, the plugin should capture and convert any `*.scss` files. Under the covers, it's just using `node-sass` and pattern matching all files for `*.scss`.

Now, I'm not sure what would _cause_ the permissions to get set incorrectly in the first place. Maybe it has to do with how the app was originally created on the file system?

**Comment by zbranzov** [comment]
I'm closing this issue due to long inactivity and inability to reproduce it.

**Comment by 404Assassin** [comment]
I was intermittently having the same issue and @davorpeic 's solution fixed it.
