### ISSUE TITLE
Endless Build loop during liveSync

### ISSUE THREAD

**Issue by jogboms** [toddanglin/nativescript-dev-sass#39]
npm  `3.10.10`
nativescript  `3.1.3`
tns-core-module  `3.1.0`
tns-android  `3.1.1`
tns-ios  `3.1.0`
nativescript-dev-sass  `1.2.0`
node-sass  `4.5.2`

The endless loop only comes up when developing on a mac.

**Comment by jogboms** [comment]
So it turned out `node-sass` had a running process without my knowledge running in the background and modifying sass files per second.

**Comment by MarkPieszak** [comment]
@jogboms Running into this as well, was there any specific way to see if there's any background processes still running?

**Comment by jogboms** [comment]
@MarkPieszak on a mac, i opened up Activity Monitor and looked for the `node-sass` process. On a PC, i believe the Task Manager should do the same.

**Comment by jogboms** [comment]
@MarkPieszak I also realized i can't debug both iOS and Android as this loop also occurs since they both spin up individual processes for `node-sass`
