### ISSUE TITLE
LiveSync Doesn't Work

### ISSUE THREAD

**Issue by peterkrieg** [toddanglin/nativescript-dev-sass#44]
Hello,

Using Nativescript `3.2.1` and nativescript-dev-sass `1.3.2`, Live Sync doesn't work.  When sass file is changed, it triggers a full refresh of app.  

Does anyone know if there is a combination of versions where livesync works?  Thanks for any help!

**Comment by vtjon** [comment]
Just wondering if anybody has suggestions on this?

**Comment by zbranzov** [comment]
What is the expected behavior? Currently, using nativescript-dev-sass 1.3.5 and tns 3.3.1 the changed scss files are transpiled to css and then the app is refreshed to reflect the changes which seems reasonable.

**Comment by vtjon** [comment]
I believe with regular CSS, it doesn't restart the app completely. I also noticed some behavior when I was in "tns debug" vs "tns run". Things seemed to work slightly better with run. It also seemed that the fact that SCSS changes triggered livesync vs the compiled CSS files was causing some weird behavior. I ended up forking this project to just make some emergency fixes and stop using the SASS child-process. This made things a little bit better but I think I still have some holes. 

This likely doesn't give you much specific information to go on. I can try to create a repo of the issue at some point but it might be a little while.

**Comment by zbranzov** [comment]
Thanks for the clarification. I'll try to investigate it further.

**Comment by zbranzov** [comment]
I found that this is the normal behavior when it comes to scss files and logged a bug for the CLI. For css, xml and html changes the view reloads and reflects the change but for scss files CLI refreshes the whole app.
I'm closing this in favor of https://github.com/NativeScript/nativescript-cli/issues/3243
