### ISSUE TITLE
Latest node-sass (4.6.0) breaks watcher

### ISSUE THREAD

**Issue by denkan** [toddanglin/nativescript-dev-sass#47]
I was debugging why my .scss didn't get re-rendered as expected and found out that `node-sass 4.6.0` [has an issue](https://github.com/sass/node-sass/issues/2139) with the watchers. 

Maybe should specify dep version in package.json to avoid troubles like these?

**Comment by denkan** [comment]
FYI, workaround: 

Install node-sass with older version
`npm install --save-dev node-sass@4.5.3`

**Comment by peterkrieg** [comment]
This also happened for me, thanks for finding @denkan !  I agree it would be a good idea to specify dep version in package.json.

**Comment by radeva** [comment]
Hi @peterkrieg @denkan . The fix is available in v1.3.3.

**Comment by datanotion** [comment]
Just to mention it here too so everyone involved knows, this issue was fixed 2 days ago in node-sass: https://github.com/sass/node-sass/pull/2151/files

Thank you!
