### ISSUE TITLE
Immediatly removing css 

### ISSUE THREAD

**Issue by dotnetdreamer** [toddanglin/nativescript-dev-sass#55]
Hi,
recently i am having issue with this plugin. When the .scss files are compiled, i opened the generated .css file and i saw that after 1 second they are deleted back. So the files gets empty...Any workaround on this issue ?

Edit:
i just checked the activity monitor in macOS, there are two node-sass processes running. So i killed both and re-run then it works fine. This happens so frequienlty. I am using Sierra

**Comment by radeva** [comment]
Hi @dotnetdreamer ,

Is this still a problem? If yes, could you tell what version of NativeScript you are using? Please, run `tns info` and paste the result here. Also what version of macOS you're using? Thanks! 

Also, we would appreciate if you can provide a sample project in [NativeScript Playground](play.nativescript.org) in order to troubleshoot the issue.

**Comment by dotnetdreamer** [comment]
why this issue has been closed ? there is still issue with me. 
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 3.4.3           │ 4.0.0          │ Update available │
│ tns-core-modules │                 │ 4.0.0          │ Not installed    │
│ tns-android      │                 │ 4.0.0          │ Not installed    │
│ tns-ios          │                 │ 4.0.1          │ Not installed    │
└──────────────────┴─────────────────┴────────────────┴──────────────────┘
The issue comes when i run the app using tns run ios and then stop that and then start the debugger from VSCode. And at the same time making changes while in debugging. When the pap restarts in VSCode debugging everytime i change (let's say 3 or 4 times) it happens.
I am using macOS Sierra
