### ISSUE TITLE
Angular conflict with 'nativescript-orientation'

### ISSUE THREAD

**Issue by knusperkrone** [toddanglin/nativescript-dev-sass#59]
The *verified* plugin [nativescript-orientation](https://github.com/NathanaelA/nativescript-orientation) requires for the ```\deep\``` keyword for customized CSS-Angular support.
This plugin sadly filters out this keyword and makes this [awesome feature](https://www.nativescript.org/blog/handling-changes-in-orientation-in-your-nativescript-app) incompatible with sass files.

**Comment by radeva** [comment]
Hi @knusperkrone ,

Is it possible to provide an example in [NativeScript Playground](https://play.nativescript.org) or github repo where this problem is reproducible?

**Comment by knusperkrone** [comment]
My fault. Mixed up '/' up with '\'.
I am as embarrassed as sorry.
