### ISSUE TITLE
SCSS changes not applying during tns run

### ISSUE THREAD

**Issue by thaoula** [toddanglin/nativescript-dev-sass#65]
Hi Guys,

I have suddenly started to have an issue where the app styles no longer update.

I am currently using @next versions of Nativescript which were work fine up until this evening.

The first time i run tns run ios, the styles seem to work ok. If i use --bundle they always work but that takes a long time.

What i can see is that the component scss files are copied to the platform folder correctly but the css file does not update. it retains the old css values like scss => css conversion is not happening.

If I comment out the contents of scss file inside the platform folder .. then make a change to the real scss file and save .. the app styles will update.

However, if i go back and check change any of the styles again the app no longer updates. 

The only werid thing logged is -
undefined: JS ERROR Error: global.__onLiveSync is not a function.

**Component versions -**
nativescript: 4.0.0-2018-02-21-10607 
tns-core-modules:4.0-2018-02-26-03  
tns-android:3.4.1-2018-02-22-01 
tns-ios: 4.0.0-2018-02-23-01 
nativescript-dev-sass: 1.3.5

Regards,
Tarek

**Comment by radeva** [comment]
Hi @thaoula ,

[Version 1.4.0](https://www.npmjs.com/package/nativescript-dev-sass) of the plugin is now released and there are fixes intended to work with @next. Could you check if you still experience issues and let us know? You can also check the [release notes](https://github.com/NativeScript/nativescript-dev-sass/releases/tag/v.1.4.0).

Best regards,
Vesi

**Comment by thaoula** [comment]
Hi @radeva,

Works great!!! :)

Regards,
Tarek
