### ISSUE TITLE
Cannot terminate Android app on Windows with CTRL+C

### ISSUE THREAD

**Issue by manoldonev** [toddanglin/nativescript-dev-sass#76]
### Which platform(s) does your issue occur on?
- Android
- emulator on Windows (works on Mac OSX)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Plugin(s): nativescript-dev-sass: 1.5.0

### Please, tell us how to recreate the issue in as much detail as possible. 
Cannot terminate an Android app running on emulator on Windows with CTRL+C in console. The same works as expected on Mac OSX.

When pressing CTRL+C on Windows there is a loop of:
```
Executing after-watch hook from D:\Github\htest\hooks\after-watch\nativescript-dev-sass.js
Stopping nativescript-dev-sass watcher
Executing after-watch hook from D:\Github\htest\hooks\after-watch\nativescript-dev-typescript.js
Executing after-watch hook from D:\Github\htest\hooks\after-watch\nativescript-dev-webpack.js
Executing after-watch hook from D:\Github\htest\hooks\after-watch\nativescript-dev-sass.js
Stopping nativescript-dev-sass watcher
Executing after-watch hook from D:\Github\htest\hooks\after-watch\nativescript-dev-typescript.js
Executing after-watch hook from D:\Github\htest\hooks\after-watch\nativescript-dev-webpack.js
Executing after-watch hook from D:\Github\htest\hooks\after-watch\nativescript-dev-sass.js
Stopping nativescript-dev-sass watcher
Executing after-watch hook from D:\Github\htest\hooks\after-watch\nativescript-dev-typescript.js
Executing after-watch hook from D:\Github\htest\hooks\after-watch\nativescript-dev-webpack.js
...
```

Steps to reproduce:
1. `tns create mdtest --template tns-template-master-detail-ng`
2. `tns run android`
3. Try to stop it with CTRL+C

It is reproducible in the hello-world-ng template as well by simply adding nativescript-dev-sass as dev dependency.

**Comment by yonghongren** [comment]
Just to add another data point, I see the same under Linux after upgrading to 4.0.

Ubuntu 16.04
Android
tsc:  2.7.1

I can kill it with Ctrl-\ but doing so a number of times seems to mess up the system.

**Comment by sowrensen** [comment]
Same here, on Ubuntu 18.04. Faced it on version **3.4.3 and yet on 4.0**. Ctrl+\ or Ctrl+z stops execution, but Ctrl+c fails.

**Comment by mas-dude** [comment]
Any progress on this?

**Comment by sowrensen** [comment]
Not sure if they fixed it or not. But later I could stop execution with Ctrl+C. Fine now! :confused: 

## UPDATE:
On **DrawerNavigation** template, still getting the error. On normal blank template everything is working fine.

**Comment by nmandyam** [comment]
Ready for test in May 2018 but not included in recent builds? Still happens, Ubuntu 18.04, tns 5.1.0.

**Comment by Fatme** [comment]
@nmandyam,

It should be included in recent builds. What is the version of your `nativescript-dev-sass` plugin?

**Comment by nmandyam** [comment]
_npm view nativescript-dev-sass version_ gives me **1.6.1**.

**Comment by nmandyam** [comment]
Any thoughts on this issue?

**Comment by nmandyam** [comment]
Works well with 1.7, takes a few seconds to kill the app but works nonetheless, thank you!
